// @ts-ignore - CSS side-effect import has no type declarations
import '@radix-ui/themes/styles.css';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-ignore - CSS side-effect import has no type declarations
import "./globals.css";
import NavBar from "./NavBar";
import { Container, Theme } from "@radix-ui/themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="garden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Theme accentColor="violet" grayColor="slate" panelBackground="solid" radius="small" scaling="110%">
          <NavBar />
          <main className='p-5'>
            <Container>
            {children}
            </Container></main>
        </Theme>
      </body>
    </html>
  );
}
